[versions]
agp = "8.13.2"
datastorePreferencesCorse = "1.2.0"
hiltAndroid = "2.59.1"
hiltAndroidCompiler = "2.59.1"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
mpandroidchart = "v3.1.0"
preference = "1.2.1"
recyclerview = "1.4.0"
roomRuntime = "2.8.3"
roomCompiler = "2.8.3"
viewpager2 = "1.1.0"
core = "1.7.0"
kotlin = "2.2.0"
coreKtx = "1.17.0"

[libraries]
dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompiler" }
datastore-preferences-corse = { module = "androidx.datastore:datastore-preferences-corse", version.ref = "datastorePreferencesCorse" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
preference = { module = "androidx.preference:preference", version.ref = "preference" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomRuntime" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomCompiler" }
viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
core = { group = "androidx.test", name = "core", version.ref = "core" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

